window.works = [
  [
    "1",
    "Dehancer Short",
    "Advertisement",
    "2024",
    "This cinematic short was fully color graded using the Dehancer plugin, bringing a rich analog look to every frame. With film emulation, authentic grain, halation, and bloom, Dehancer helped us create a textured, emotional visual experience that feels both modern and timeless. Special thanks to Dehancer for sponsoring this project.",
    "https://www.youtube.com/watch?v=QZgxj8_8Vlg",
  ],
  [
    "2",
    "De Diefte",
    "Movie",
    "2025",
    "De Diefte is a Belgian feature film directed by Raf De Graeve, exploring the 1934 theft of the 'Just Judges' panel from the Ghent Altarpiece. Blending historical facts with fiction, the story follows Hubert, a man uncovering his grandfather's ties to the infamous art heist.",
    "https://scontent-bru2-1.xx.fbcdn.net/v/t39.30808-6/489147588_122151170168571096_8613332434549729350_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=f727a1&_nc_ohc=Mjr1PChKbCEQ7kNvwHjPBu5&_nc_oc=Adlu1wVXIovQR2kUuocSkvkly1YzDh6GyqUHMu6pg8cBcMJUf8-7s7s2m0TPCzGHrxQMnynhV2-UrxFZj3X7IS2t&_nc_zt=23&_nc_ht=scontent-bru2-1.xx&_nc_gid=KEMx7W4yX9AuVM7LsfK6SQ&oh=00_AfE2Aa-Uv_cZbZT7Dk63Td5gh2-7XRKLTUWgmw1jdfQxvw&oe=681C4D57",
  ],
  [
    "3",
    "Crodino Advert",
    "Advertisement",
    "2022",
    "This spec commercial for Crodino marks our first exercise in product promotion and visual storytelling. From lighting and styling to camera movement and color grading, every detail was crafted to highlight the product's refreshing character and premium feel. While not an official ad, this project demonstrates our creative approach and technical skills in commercial filmmaking.",
    "https://www.youtube.com/watch?v=NRXTWbl0PDc",
  ],
  [
    "4",
    "Drone Showcase",
    "Advertisement",
    "2023",
    "This aerial reel highlights our drone cinematography capabilities — capturing dynamic perspectives, smooth tracking shots, and cinematic landscapes. Whether for events, real estate, or commercial projects, we offer high-quality drone footage to elevate any production. Drone services are now part of our full videography offering.",
    "https://www.youtube.com/watch?v=O5JJyzwZ4Y8",
  ],
  [
    "5",
    "Connie & Bernard",
    "Wedding",
    "2024",
    "This cinematic wedding film captures the love and joy of Connie & Bernard’s special day. From emotional vows to vibrant celebrations, we documented every moment with care and storytelling in mind. Weddings are part of our videography services — we’re here to turn your day into a timeless film.",
    "https://www.youtube.com/watch?v=8Y7KrIOjGI4",
  ],
];
